services:
  go:
    build: ./.docker/dev
    container_name: scootin-go
    hostname: scootin-go
    environment:
      CGO_ENABLED: 0
      GO111MODULE: "on"
    volumes:
      - .:/app:cached
    working_dir: /app
    command: go run main.go
    ports:
      - 8081:80
      - 64782:64782
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: scootin-mysql
    hostname: scootin-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data: { }
